version: 2.1

jobs:
  test:
    docker:
      - image: circleci/openjdk:17-ea-buster-node-browsers-legacy
    steps:
      - checkout
      - run:
          name: Tests with JaCoCo coverage
          command: mvn clean verify jacoco:report
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:checkstyle

      - run:
          name: Copy Javadoc to DocJava directory
          command: |
            mkdir -p DocJava
            mv target/site/testapidocs/fr/univavignon/pokedex/api/* DocJava/
            mv DocJava/* .

workflows:
  upload-to-codecov:
    jobs:
      - test:
          filters:
            branches:
              only: master
  build:
    jobs:
      - test
