version: 2.1

jobs:
  test:
    docker:
      - image: circleci/openjdk:17-ea-buster-node-browsers-legacy
    steps:
      - checkout
      - run:
          name: Tests with JaCoCo coverage
          command: mvn clean verify jacoco:report
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:checkstyle

      - run:
          name: Push Javadoc to GitHub Pages
          command: |
            git config --global user.email "thom.croiz18@gmail.com"
            git config --global user.name "CroizetThomas"
            git checkout -b gh-pages
            mv target/site/testapidocs/fr/univavignon/pokedex/api/* docs/
            git add docs
            git commit -m "Update Javadoc [ci skip]"
            git push origin HEAD:gh-pages

workflows:
  upload-to-codecov:
    jobs:
      - test:
          filters:
            branches:
              only: master
  build:
    jobs:
      - test
