version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  test:
    docker:
      - image: circleci/openjdk:17-ea-buster-node-browsers-legacy
    steps:
      - checkout
      - run:
          name: Tests with JaCoCo coverage
          command: mvn clean verify jacoco:report
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml

workflows:
  upload-to-codecov:
    jobs:
      - test:
          filters:
            branches:
              only: master
  build:
    jobs:
      - test
