version: 2.1

jobs:
  test:
    docker:
      - image: circleci/openjdk:17-ea-buster-node-browsers-legacy
    steps:
      - checkout
      - run:
          name: Configuration de l'identité Git
          command: |
            git config --global user.email "thom.croiz18@gmail.com"
            git config --global user.name "CroizetThomas"
      - run:
          name: Tests avec couverture JaCoCo
          command: mvn clean verify jacoco:report
      - run:
          name: Générer Javadoc
          command: mvn javadoc:javadoc
      - run:
          name: Exécuter Checkstyle
          command: mvn checkstyle:checkstyle

workflows:
  upload-to-codecov:
    jobs:
      - test:
          filters:
            branches:
              only: master
  build:
    jobs:
      - test
